server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

constants:
  file:
    upload-directory: home/download/images
    user-pic: /user
    store-pic: /store
    store-banner-pic: /store/banner
    store-menu-pic: /menu
  open-feign:
    action:
      url: hanip-action
  jwt:
    issuer: green502@green.com #토큰 발행자
    bearer-format: JWT

    claim-key: signedUser
    secret-key: EvenTheDarkestNightWillEndAndTheSunWillRiseAgain2025!

    domain: greenart.n-e.kr

    access-token-cookie-name: access-token
    access-token-cookie-path: /
    access-token-cookie-validity-seconds: 86_400
    access-token-validity-milliseconds: 86_400_000

    refresh-token-cookie-name: refresh-token
    refresh-token-cookie-path: /hanip-actor/api/user/reissue
    refresh-token-cookie-validity-seconds: 1_296_000
    refresh-token-validity-milliseconds: 1_296_000_000

eureka:
  client:
    enabled: false

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

spring:
  application:
    name: hanip-actor
  cloud:
    kubernetes:
      discovery:
        enabled: true
      reload:
        enabled: true
        strategy: refresh
    loadbalancer:
      enabled: true
  datasource:
    url: jdbc:log4jdbc:mariadb://112.222.157.157:5011/final_actor
    username: green1
    password: spring502
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jackson:
    default-property-inclusion: non_null
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        format_sql: true
        order_updates: true
  security:
    oauth2:
      client:
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize # 카카오 인증처리 URL
            token-uri: https://kauth.kakao.com/oauth/token #토큰(JWT) 받을 때
            user-info-uri: https://kapi.kakao.com/v2/user/me # 유저 정보 얻을 때 사용하는 URL
            user-name-attribute: id
          naver:
            authorization-uri: http://nid.naver.com/oauth2.0/authorize
            token-uri: http://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
        registration:
          kakao:
            client-name: Kakao
            client-id: df86f2c75ac6f162814e46850f6bb6c3
            client-secret: lvhWJP6ErRSY4eRUz1SrMBwO35ouvHkT
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
            # baseUrl: 서버가 돌아가고 있는 host 주소값
            # action: login
            # registrationId: kakao
            # 결과 (만약 localhost:8080으로 동작 중이면)
            # http://localhost8080/login/oauth2/code/kakao
          naver:
            client-name: Naver
            client-id: FLXBNnWxtqTBo2VIwaBh
            client-secret: aNATVdEvpN
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/{action}/oauth2/code/{registrationId}"
            scope:
              - name
              - email
              - profile_image
              - nickname
  lifecycle:
    timeout-per-shutdown-phase: 30s

mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mappers/**/*.xml